config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :signs
  resources :feedbacks

  get "about" => "signs#about", as: :about
  get "contact" => "signs#contact", as: :contact
  get "Today's Data" => "astrodatas#show", as: :todaysdata
  
  root 'signs#index'

end

app/models/sign.rb
class Sign < ActiveRecord::Base
	has_attached_file :image_1, styles: { medium: "300x300>", thumb: "175x175>" }, 
    :default_url => "http://www.cabanasdechile.com/res/img/common/missing-thumbnail.jpg",
    :storage => :s3,
    :bucket => 'astro-logical-assets'
    validates_attachment_content_type :image_1, :content_type => /\Aimage\/.*\Z/
end
   	#validates_presence_of :slug
	# def to_param
	# 	slug
	# end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  before_action :set_sign, only: [:show, :edit, :update, :destroy]


  def index
    @signs= Sign.all
  end

  def about
  end

  def contact
  end

  def show
       
    #   begin
    #   # @sign=Sign.find_by_slug(params[:id])
    
    #   # respond_to do |format|
    #   #   format.html # show.html.erb
    #   #   format.json {render json @sign}
    #   # end

    # rescue
    #   redirect_to root_path, notice: "Unavailable"
    # end
  end


  def new
    @sign = Sign.new
  end

  def edit
  
  end


  def create
    @sign = Sign.new(sign_params)
    if @sign.save
        #flash[:notice] = "New shirt created"
        redirect_to sign_path(@sign), notice: "New sign created."
    else
      render :new
    end
  end


  def update
      @sign.update(sign_params)
  end


  def destroy
    @sign.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign
      @sign = Sign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_params
      params.require(:sign).permit(:name, :image_1, :birth_range, :horoscope, :slug)
    end
end

app/views/signs/_form.html.erb
<%= form_for(@sign) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_range %><br>
    <%= f.text_field :birth_range %>
  </div>
  <div class="field">
    <%= f.label :horoscope %>
    <%= f.text_field :horoscope %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug%>
  </div>
  <div class="field">
    <%= f.file_field :image_1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signs/about.html.erb
 <h1>About This App</h1>

app/views/signs/edit.html.erb
<h1>Editing Sign</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign %> |
<%= link_to 'Back', signs_path %>
<%= link_to 'Delete', sign_path(@sign), method: :delete %>

app/views/signs/index.html.erb
<% @signs.each do |sign| %>
	    <div class="col-mod-2">
				     <div class="sign_image"> 
			        	<p><%=link_to image_tag(sign.image_1.url(:thumb)), sign_path(sign.id)%></p>
			       	</div>
			    </div>
		
 <% end %>

app/views/signs/new.html.erb
<h1>New Sign</h1>

<%= render 'form' %>

<%= link_to 'Back', signs_path %>

app/views/signs/show.html.erb
<div class="sign_image_2"><%= image_tag(@sign.image_1.url(:medium))%></div>
<p> <%= @sign.birth_range %></p>
<p> Horoscope for <%= Time.now.strftime("%m/%d/%Y") %></p>
<p> <%= @sign.horoscope %></p>
<p><%= link_to "Leave Feedback", new_feedback_path(@feedback) %></p>


<%= link_to 'Edit', edit_sign_path(@sign) %> |
<%= link_to 'Back', signs_path %>